### ISSUE TITLE
[BUG] `npm i` fails for utilities frontend for node version higher than 11

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/Social-Bot-Framework#46]
1. **Summary** - I tried installing new packages on the utilities frontend when I noticed that the `install` command fails. 
2. **Bug Details** :
   1. **What?** - Running `npm i` in `Utilities Frontend\app\` directory results in an error. I am using node version `v14.16.1`. The following log is produced:
```txt
$ npm i 

> bufferutil@1.2.1 install C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil
> node-gyp rebuild


C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(25,30): error C2039: 'Handle': is not a member of 'v8' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8-platform.h(16): message : see declaration of 'v8' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(25,36): error C2061: syntax error: identifier 'Handle' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(33,14): error C2065: 'target': undeclared identifier [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(33,1): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(6482,46): message : see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(49,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(56,1): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(67,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(69,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(88,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(89,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(91,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(92,1): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2869,40): message : see declaration of 'v8::Value::Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(93,1): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2869,40): message : see declaration of 'v8::Value::Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(114,12): error C2065: 'Handle': undeclared identifier [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(114,19): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(3664): message : see declaration of 'v8::Object' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(114,27): error C2065: 'target': undeclared identifier [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(114,6): error C2182: 'init': illegal use of type 'void' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(115,1): error C2448: 'init': function-style initializer appears to be a function definition [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\src\bufferutil.cc(120,1): warning C4312: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil\build\bufferutil.vcxproj]
←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mbuild error←[0m 
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.emit (events.js:315:20)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mSystem←[0m Windows_NT 10.0.22000
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcommand←[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcwd←[0m C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\bufferutil
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode -v←[0m v14.16.1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode-gyp -v←[0m v5.1.0
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnot ok←[0m
←[0m
> utf-8-validate@1.2.0 install C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate
> node-gyp rebuild


C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  validation.cc
  win_delay_load_hook.cc
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(107,30): error C2039: 'Handle': is not a member of 'v8' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8-platform.h(16): message : see declaration of 'v8' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(107,36): error C2061: syntax error: identifier 'Handle' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(113,14): error C2065: 'target': undeclared identifier [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(113,1): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(6482,46): message : see declaration of 'v8::FunctionTemplate::GetFunction' (compiling source file ..\src\validation.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(132,1): error C2660: 'v8::Value::ToObject': function does not take 0 arguments [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(2822,44): message : see declaration of 'v8::Value::ToObject' (compiling source file ..\src\validation.cc) [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(141,12): error C2065: 'Handle': undeclared identifier [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(141,19): error C2275: 'v8::Object': illegal use of this type as an expression [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Users\ben\AppData\Local\node-gyp\Cache\14.16.1\include\node\v8.h(3664): message : see declaration of 'v8::Object' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(141,27): error C2065: 'target': undeclared identifier [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(141,6): error C2182: 'init': illegal use of type 'void' [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(142,1): error C2448: 'init': function-style initializer appears to be a function definition [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\src\validation.cc(147,1): warning C4312: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size [C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate\build\validation.vcxproj]
←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mbuild error←[0m 
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.emit (events.js:315:20)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mSystem←[0m Windows_NT 10.0.22000
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcommand←[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcwd←[0m C:\Repositories\Social-Bot-Framework\Utilities Frontend\app\node_modules\utf-8-validate
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode -v←[0m v14.16.1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode-gyp -v←[0m v5.1.0
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnot ok←[0m
←[0mnpm WARN SocialBotFramework@1.0.2 No repository field.
npm WARN SocialBotFramework@1.0.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utf-8-validate@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utf-8-validate@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ben\AppData\Roaming\npm-cache\_logs\2021-11-23T22_26_37_769Z-debug.log
```
   2. **Where?** - In the `Utilities Frontend\app\` directory
   4. **How?/Current state** - Just call in `npm i` in the `Utilities Frontend\app\` directory.

**Comment by lakhoune** [comment]
The issue seems to be linked to the node version 10 seems to work
